### ISSUE TITLE
Sourcemaps

### ISSUE THREAD

**Issue by benriordan** [meteor-typescript/meteor-typescript-compiler#17]
Sourcemaps would be extremely helpful. (`tsc --sourcemap`)
I'll look into this as well, I may or may not be smart enough to figure it out.

**Comment by benriordan** [comment]
Looks like the following functionality was removed in 2.0
https://github.com/meteor-typescript/meteor-typescript-compiler/pull/5/files

**Comment by orefalo** [comment]
Should be trivial 

Will give it a try next weej

**Comment by orefalo** [comment]
just published the latest version. it's late and i didn't get a change to unit test it. plz let me know if it works. if it doesn't adjust the code - tks

**Comment by orefalo** [comment]
looks fixes, closing. thank you

**Comment by benriordan** [comment]
Thank you so much!!!
