### ISSUE TITLE
My install instructions must be incomplete...?

### ISSUE THREAD

**Issue by ericoe** [meteor-typescript/meteor-typescript-compiler#18]
I did the following to test. Create a sample app, add the ts compiler package, run.
Note, there are no .ts files in this test.

    meteor create tstest
    cd tstest
    meteor add meteortypescript:compiler
    #meteortypescript:compiler  added, version 2.0.6
    meteor

```
=> Started proxy.                             
Could not find tsc binaryeTypescript` fr...  |
typescript-compiler:The file "zzz.ts-compiler.ts" has been created to help batch compilation of typescript assets. Please ignore it from your source control.
=> Started MongoDB.                           
   Building the application                  -
Compiling TypeScript os files...
Done
   Building the application                  -
Compiling TypeScript web.browser files...
Done
=> Errors prevented startup:                  
   
   While building the application:
   /Users/EricO/Documents/dev/meteor/ts/zzz.ts-compiler.ts:1:1: 
   /bin/sh: : command not found
   
   
=> Your application has errors. Waiting for file change.
```

**Comment by orefalo** [comment]
check your path, tsc MUST be in the path.   the module complains that it cannot find it.   Could not find tsc binaryeTypescript
also, the plugin creates one .ts file - zzz.ts-compiler.ts 

     On Friday, February 27, 2015 2:17 PM, Eric <notifications@github.com> wrote:
   

 I did the following to test. Create a sample app, add the ts compiler package, run.
Note, there are no .ts files in this test.meteor create tstest
cd tstest
meteor add meteortypescript:compiler
#meteortypescript:compiler  added, version 2.0.6
meteor
=> Started proxy.                             
Could not find tsc binaryeTypescript` fr...  |
typescript-compiler:The file "zzz.ts-compiler.ts" has been created to help batch compilation of typescript assets. Please ignore it from your source control.
=> Started MongoDB.                           
   Building the application                  -
Compiling TypeScript os files...
Done
   Building the application                  -
Compiling TypeScript web.browser files...
Done
=> Errors prevented startup:                  

   While building the application:
   /Users/EricO/Documents/dev/meteor/ts/zzz.ts-compiler.ts:1:1: 
   /bin/sh: : command not found


=> Your application has errors. Waiting for file change.

**Comment by ericoe** [comment]
So it turns out (embarrassing to admit) something in my node install corrupted my local dir tree. I had to reset permissions... all good now.
Thanks!
