### ISSUE TITLE
Use project-specific 'tsc' instead of global 'tsc'.

### ISSUE THREAD

**Issue by cakoose** [meteor-typescript/meteor-typescript-compiler#21]
In a Node.js-based project, I can use 'npm' to install a project-specific version of 'tsc' and have Grunt/Gulp use that instead of the global 'tsc'.  This eliminates the chance of a mismatch between the 'tsc' version expected by my source code and whatever 'tsc' happens to be installed globally.

Is there a way to do this with meteor-typescript?

**Comment by orefalo** [comment]
I think what you need is a parameter which points to the compiler to use. Enhancement

**Comment by barbatus** [comment]
TypeScript API is used instead of `tsc` for a while already.
There is no reason to re-configure API version for diff projects since i believe each new API version will be backward compatible.
