### ISSUE TITLE
TS files in packages

### ISSUE THREAD

**Issue by theduke** [meteor-typescript/meteor-typescript-compiler#22]
I just tried to use this package, and ran into a problem:

I structure all my projects by writing many custom Meteor packages, 
so I will have an example structure like this:

```
myapp/
myapp/package.js
myapp/collections.ts
```

And in package.js:
```javascript
Package.onUse(function(api) {
  var both = ['server', 'client'];
  api.addFiles([
    'collections.ts'
  ], both);
});
```

I would either like to do ```api.addFiles('collection.js'...``` or ```api.addFiles('collection.ts')``` and have the .js file automatically created and then added to the resulting code.

The only way I can think of right now is api.adding the *.js files, and run the tsc compiler manually, but this  is quite cumbersome.

Ideally, I would just add the *.ts file and Meteor would compile it and pick it up automatically.
Any suggestions on how to achieve this?

**Comment by awsp** [comment]
+1 for this, I ran into the exact same situation. 

I modularize my projects in all self contained packages. But when I try to re-write it using .ts, Meteor fail to pick up *.ts files. 

I have *.ts files running with problem without in package form.

**Comment by divyakumarjain** [comment]
+1

Need support for ts files in package

**Comment by divyakumarjain** [comment]
Does adding api.use('meteortypescript:compiler') in package.js file of package helps?

**Comment by realyze** [comment]
I have the same issue and `api.use('meteortypescript:compiler')` didn't change anything.

**Comment by krizka** [comment]
+1 whyyyy i spent 2 hours finding the reason... and it's so simple. it's just not work.

**Comment by realyze** [comment]
@orefalo Fixing this would definitely make this great package even greater! ;-)

**Comment by D1no** [comment]
Meteor Preview 1.2 is out with a way more fine-grained way to intercept the build process. Potentially allowing us to fluently use modules in the package and app folder. Any ideas?
meteor/meteor#4800

**Comment by orefalo** [comment]
Cool! Will look into it

**Comment by divyakumarjain** [comment]
Do let us know if there is WIP branch which we can try a fix for this.

Also would like to know if supporting export from package is it possible. I can open a new issue for this question.

**Comment by fignuts** [comment]
This looks like it is still broken. Any leads on a fix?

**Comment by vangorra** [comment]
I've been able to get this working. It requires a local file compiler but works.
https://gist.github.com/vangorra/7ea7ea87a8df0484db98

**Comment by barbatus** [comment]
Obsolete
