### ISSUE TITLE
problems when file is called main.ts

### ISSUE THREAD

**Issue by pgrm** [meteor-typescript/meteor-typescript-compiler#23]
I've set it up in Windows and it works great, however when I created the files `server/main.ts` and `client/main.ts`, they got compiled (I could get compile errors) - but never executed, neither on client nor on the server.

Renaming any of the file from `main.ts` to anything else (for instance `server.ts` or `index.ts`) "fixed" the problem. It isn't really fixed, as I'd like to be able to create a file with the name `main.ts`. Maybe I can instead create `main.something.ts` - I'll check that later, but any idea why `main.ts` isn't working?

**Comment by pgrm** [comment]
I've checked it and `main.anything.ts` is also not working

**Comment by julius** [comment]
Thanks so much @pgrm . Was stuck on this for quite a bit.

And this has nothing to do with Windows btw. On Ubuntu, it seems to compile the main.ts file (I get compilation errors). But the code in it seems to be totally ignored. Changing the filename fixes it.

**Comment by barbatus** [comment]
Seems to be not an issue any more.
