### ISSUE TITLE
Should '--module' flag be turned on?

### ISSUE THREAD

**Issue by keekun** [meteor-typescript/meteor-typescript-compiler#27]
I add DefinitelyTyped as a submodule into my app and try : 
 import Sequelize = require('sequelize')
but cannot compile successfully:

error TS1148: Cannot
   compile external modules unless the '--module' flag is provided.

It seems that some define files of DefinitelyTyped are using external modules.
Any good way to make them work?

**Comment by barbatus** [comment]
This shouldn't be an issue any more. Please try the last version.
