### ISSUE TITLE
Typescript 1.5 support

### ISSUE THREAD

**Issue by samuba** [meteor-typescript/meteor-typescript-compiler#32]
Typescript 1.5 is officially stable. This package should support it.

**Comment by AugustNagro** [comment]
+ 1

**Comment by jpadvo** [comment]
Here's code with 1.6 and jsx support, if anybody needs it: https://github.com/meteor-typescript/meteor-typescript-compiler/pull/33

**Comment by samuba** [comment]
we can close this one
