### ISSUE TITLE
Unknown compiler option 'jsx'

### ISSUE THREAD

**Issue by kataras** [meteor-typescript/meteor-typescript-compiler#35]
Error on server's console, Unknown compiler option 'jsx' when I add .tsx (JSX(React) for Typescript) files into my projects , (I dont have any .jsx files, just the .tsx ) .

Meteor: 1.2.0.2
OS: Windows 10
Typescript : 1.6.2 ( both npm and visual studio's version for 1.6.2  (1.6.3.0) )

**Comment by Rouby** [comment]
Make sure you are indeed using TS 1.6. I still had the 1.5 folder in "C:\Program Files (x86)\Microsoft SDKs\TypeScript" and deleting that fixed this issue for me.

**Comment by kataras** [comment]
I have Typescript 1.6, I 'm working with ts 1.6 from it's first day come out I never had this problem before...

**Comment by Rouby** [comment]
Do you have only typescript 1.6 or some older version concurrently installed? Meteor will not necessarily use the same version as visual studio (or other tools for that matter).

**Comment by kataras** [comment]
I deleted all old typescript 1.5 folders I had, I have only Typescript 1.6 on my machine. Right now I'm trying to create a new project using only .tsx to see if that works...I will let you know

**Comment by kataras** [comment]
I am 99% sure that I have only TS 1.6 on my machine, because I did uninstall/delete TS 1.5 before install TS 1.6 ( npm & visual studio plugin). But for sure, how can I see what version of typescript the meteor uses?

**Comment by Rouby** [comment]
Type into the console "tsc --version"

**Comment by kataras** [comment]
yes this way I see typescript version on my pc, 1.6.2 .

**Comment by kataras** [comment]
This is working for me: https://github.com/nodets/meteor-typescript/blob/master/src/tsCompile.js , copy and paste it to your library too in order to .tsx work on windows machines :)

**Comment by crazy2be** [comment]
I had the same problem in an unrelated project. In my case, it turned out that I had installed tsc rather than typescript. Apparently both packages exist in npm, but tsc is using a much older version of typescript (1.5.x), while the typescript package includes  the newer version.

**Comment by barbatus** [comment]
This seems not to be actual now. Please use the latest version.
