### ISSUE TITLE
I am getting an error "The Command line is too long."

### ISSUE THREAD

**Issue by prodogs** [meteor-typescript/meteor-typescript-compiler#37]
anyone have a clue on how to solve this?

**Comment by orefalo** [comment]
Maybe try linux...

you have to admit there is not much details...

**Comment by kataras** [comment]
https://github.com/nodets/meteor-typescript this is working for me, try this and tell me if you are getting the same error yet

**Comment by barbatus** [comment]
Please try the last versions, it's like fixed there.
