### ISSUE TITLE
While processing files : Unknown absolute import path

### ISSUE THREAD

**Issue by maxfriedmann** [meteor-typescript/meteor-typescript-compiler#38]
Hi,
I just switched from a custom grunt based typescript compilation process back to this package. I am getting the following error : 

```
While processing files with meteortypescript:compiler (for target os.windows.x86_32):
   <anonymous>: Unknown absolute import path packages/core/typedefinitions/core.d.ts
   at Error (<anonymous>)
   at multi-file-caching-compiler.js:134:21
   at Array.forEach (native)
   at multi-file-caching-compiler.js:132:33
   at multi-file-caching-compiler.js:144:68
   at
   C:\Users\me\AppData\Local\.meteor\packages\meteortypescript_compiler\3.0.0\plugin.compileTypescript.os\npm\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish
   (C:\Users\me\AppData\Local\.meteor\packages\meteortypescript_compiler\3.0.0\plugin.compileTypescript.os\npm\caching-compiler\node_modules\async\lib\async.js:317:21)
   at
   C:\Users\me\AppData\Local\.meteor\packages\meteortypescript_compiler\3.0.0\plugin.compileTypescript.os\npm\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit
   (C:\Users\me\AppData\Local\.meteor\packages\meteortypescript_compiler\3.0.0\plugin.compileTypescript.os\npm\caching-compiler\node_modules\async\lib\async.js:221:35)
   at TsCachingCompiler.processFilesForTarget (multi-file-caching-compiler.js:95:11)
   at TsCachingCompiler.processFilesForTarget (compilers/ts_caching_compiler.js:37:32)


=> Your application has errors. Waiting for file change.
```

The project is quite big, with tsc on the shell I don't get any errors. Would it be possible to extend the message a bit, for example in which file the error happened? That would speed up fixing those kind of errors dramatically....

**Comment by orefalo** [comment]
right... if only I knew where the error was raised from...

hard to help without a project structure and more details.
What file in your project references core.d.ts

**Comment by maxfriedmann** [comment]
I moved all ts files out of the project since apparently most files are referencing core.d.ts, then I spent the day yesterday trying to figure out where it comes from and it seems like it its all of them :)

Is it possible that I might not be able to include d.ts files from packages?

**Comment by maxfriedmann** [comment]
Packages aren't compiled either, still, right? So it doesn't make any sense for us right now anyway. Will come back what it also compiles packages. 

Thanks for the time!

**Comment by bubuzzz** [comment]
Is this fixed  or is this a bug? I started a fresh project with `meteor-typescript-compiler` and it gives exactly this exception. I cannot figure out how to solve this, because both Visual Studio Code and command line "tsc *.ts" can see the referent def file (`.d.ts`). This is my sample project `https://github.com/bubuzzz/ts-demo.git`. Please give some suggestions for this

**Comment by shybyte** [comment]
I have the the same problem.

**Comment by django43ru** [comment]
I got the same problem. My solution is removing this package and using gulp-typescrpt.

**Comment by ErikBjare** [comment]
Ran across the same issue, started fresh.

Perhaps the issue should be reopened?

**Comment by django43ru** [comment]
I use gulp-typescript for compiling in the complex cases, but there is an easy way, that should work in the most cases: put tsconfig.json (https://github.com/Microsoft/TypeScript/wiki/tsconfig.json) in the root of your project and then start the compiler from the command line with the command **tsc**. For example, in my last Meteor project the tsconfig.json looks like this: 
// tsconfig.json
{
    "compilerOptions": {
        "target":"es5",
        "module": "commonjs",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": false,
        "watch": true
    },
    "exclude":[
        ".meteor",
        ".vscode",
        "typings",
        "public"
    ]
}

Start compiler from the root of your project with command **tsc**, and the compiler will compile and save your <filename>.ts into the <filename>.js in the same directory. 

Don't forget to put something like this in the end of your .ts file:
// foo.ts
namespace Foo{
  export class Foo{
     ...  
  }
  ...
} 
**this.Foo = Foo;**
Then you be able to use Foo namespace in the file, where you import foo.ts
