### ISSUE TITLE
Is Babel needed?

### ISSUE THREAD

**Issue by Namek** [meteor-typescript/meteor-typescript-compiler#39]
Since TypeScript is TypeScript and it's got it's own compiler, I think that Babel/ecmascript isn't needed, I'm I wrong? I can see that's inherited from @barbatus https://github.com/barbatus/ts-compilers project but still don't understand that.

**Comment by barbatus** [comment]
Babel and TypeScript are different supersets of ES6. While they cover ES6 standard mostly identically, they have differences regarding other parts. Like built-in type-checking support (as in the case of TypeScript but not in Babel), support of ES7 experimental features out of box, or plugins support (as in the case of Babel this time but not TypeScript). Final choice is of course after you.
