### ISSUE TITLE
Getting "Cannot compile namespaces when the '--isolatedModules' flag is provided"

### ISSUE THREAD

**Issue by eyal453** [meteor-typescript/meteor-typescript-compiler#41]
This happened to me in my project so I tried it on the provided "HelloWorld" sample and wrapped the HelloWorld class with a module. 

```
'use strict';

module Whatever {
    export class HelloWorld {
        constructor(public name: string = 'World') { }

        toString() {
            return `Hello ${this.name}`;
        }
    }
}

console.log(new Whatever.HelloWorld().toString());
```

Same error. 

BTW, my machine has TSC 1.6.2 on it.

Is there a fix to this?

**Comment by bubuzzz** [comment]
it happens to me as well. my tsc version is 1.3.0. please fix. It is quite frustrated when the first basic step does not work

**Comment by bubuzzz** [comment]
issue is solved if you add the meteortypescript:typescript-libs package to meteor
