### ISSUE TITLE
The generated map file references the wrong URL to the source file. The extension is missing.

### ISSUE THREAD

**Issue by vangorra** [meteor-typescript/meteor-typescript-compiler#43]
The generated map file references the wrong URL to the source file. The extension is missing.

What is being generated:
```
{
  "version": 3,
  "sources": ["meteor://app/server/app"]
  ...
}
```

What should be generated:
```
{
  "version": 3,
  "sources": ["meteor://app/server/app.ts"]
  ...
}
```

This happens for both client and server code.

**Comment by barbatus** [comment]
This is not the issue any more. Check the last version.
