### ISSUE TITLE
meteor throws error at run time when ()=>{ } syntax is used

### ISSUE THREAD

**Issue by DmitryEfimenko** [meteor-typescript/meteor-typescript-compiler#45]
I have a simple publication that works as expected:
```
Meteor.publish('parties', function(fnName: string, terms: any) {
    Counts.publish(this, 'partiesCounts', Parties.find(params.selector), { noReady: true });
    return Parties.find({});
});
```
However, if I change the `function` to TypeScript style, meteor throws an error:
```
Meteor.publish('parties', (fnName: string, terms: any)=> {
    Counts.publish(this, 'partiesCounts', Parties.find(params.selector), { noReady: true });
    return Parties.find({});
});
```
The error I get is:
> Exception from sub parties id blahblah TypeError: Object [object global] has no method 'added'
     at Object.Counts.publish (packages/tmeasday_publish-counts/packages/tmeasday_publish-counts.js:87:1)
    ...

Any idea what's going on here?

**Comment by barbatus** [comment]
Dmitry,

you are loosing right context in the second example.

Or to be exact, `Meteor.publish` executes that callback with the special context, and  `()=>{}` overrides it with the caller's one in the second example.

**Comment by barbatus** [comment]
Seems to be outdated. Closing.

**Comment by DmitryEfimenko** [comment]
yeah, it was my lack of understanding of TS `this` workings.
Thanks for answer
