### ISSUE TITLE
Source for version 3.1.0?

### ISSUE THREAD

**Issue by mattmccutchen** [meteor-typescript/meteor-typescript-compiler#46]
I wanted to get the latest source of the meteortypescript:compiler package as a starting point for a local package.  On the [Meteor package server](https://atmospherejs.com/meteortypescript/compiler), the latest version is 3.1.0, so I assumed I wanted something at least as new.  But the version number in master is currently 3.0.1; the only commit I can find with version number 3.1.0 is f73213c.  What happened here?  Was the change of the version number back to 3.0.1 in commit 2aff55a unintentional?

**Comment by barbatus** [comment]
Yeah, there was a wrong merge that slipped through.
Anyways, this package has been updated and now uses `barbatus:typescript`. Current version is 3.2.0. Please read updated README as well.
