### ISSUE TITLE
Compile options for client and server

### ISSUE THREAD

**Issue by dbx834** [meteor-typescript/meteor-typescript-compiler#50]
Hello,

I have a question, or rather two, perhaps three. 

- How do I build differently for client and server?
- How do I share code between client and server?
- How do I build differently this shared code that will use two different Typings (main.d.ts and browser.t.ds)?

Example app, Imagine an app with this directory structure,

> - app
>   - - client
>      - index.html
>      - index.tsx
>   - - server
>      - index.ts
>   - - collections
>      - tasks.ts

The first problem is to build differently for client and server. And, the second problem is to share the code between client and server. How is this possible with the current setup?

I have searched for this elsewhere. Please also see,

- [Using shared classes for single output client and common.js based node.js code](https://github.com/Microsoft/TypeScript/issues/5094)
- [SO: share-a-common-package-between-server-and-client](http://stackoverflow.com/questions/32680943/share-a-common-package-between-server-and-client)
- [SO: sharing-typescript-classes-between-client-and-server](http://stackoverflow.com/questions/35796604/sharing-typescript-classes-between-client-and-server)

Thanks
/P

**Comment by barbatus** [comment]
I don't see how this related to this package and Meteor particular? Everybody who works with Meteor, knows about `client`, `server` folders for that two different platforms, and everything else is shared between.  You can find more in the Meteor Guide. http://guide.meteor.com/

**Comment by vjau** [comment]
I see pretty well how this is related to Typescript.
He is not asking how Meteor is working, but how you must use it with typescript.
For example, should you use multiples tsconfig.json ? How is the compiler supposed to know what is available where ?
