### ISSUE TITLE
Working with an ide

### ISSUE THREAD

**Issue by vjau** [meteor-typescript/meteor-typescript-compiler#52]
Hi,
i was usually doing all my Typescript "compilation" with Webstorm, but now i'm giving this compiler a try.
This means i don't want webstorm to emit js code anymore, so i have but a "noemit" directive in the tsconfig.json.
But as far as i understand it, when you are providing a tsconfig, it's use by the meteor-typescript-compiler.
Would it cause problems to have a noemit there ? 
Thank you

**Comment by barbatus** [comment]
Ts-compiler uses only certain options from tsconfig ignoring any other that doesn't make sense in Meteor environment. One of them is noemit.
